package com.example.peitoinfinity.domain.model

data class Exercise(
    val id: String,
    val name: String,
    val primaryMuscleGroup: MuscleGroup,
    val secondaryMuscleGroups: List<MuscleGroup>,
    val equipment: Equipment,
    val exerciseType: ExerciseType,
    val description: String,
    val difficulty: Difficulty,

    // Biomechanical metadata fields
    val aliases: List<String> = emptyList(),
    val movementPattern: String = "",
    val plane: String = "",
    val jointAction: String = "",
    val stability: String = "",
    val rangeOfMotion: String = "",
    val unilateral: Boolean = false,
    val axialLoad: String = "",
    val spinalLoad: String = "",
    val primaryMuscles: List<String> = emptyList(),
    val secondaryMuscles: List<String> = emptyList(),
    val stabilizers: List<String> = emptyList(),
    val stimulusScore: Int = 0,
    val fatigueScore: Int = 0,
    val progressionScore: Int = 0,
    val learningCurve: Int = 0,
    val versatility: Int = 0,
    val shoulderFriendly: Boolean = true,
    val kneeFriendly: Boolean = true,
    val hipFriendly: Boolean = true,
    val lowerBackFriendly: Boolean = true,
    val injuryRisk: String = "",
    val stretchBias: String = "",
    val shortenedBias: String = "",
    val constantTension: String = "",
    val peakContraction: String = "",
    val priority: String = "",
    val recommendedOrder: Int = 0,
    val recommendedSets: String = "",
    val recommendedRepRange: String = "",
    val maxWeeklyFrequency: Int = 0,
    val redundantWith: List<String> = emptyList(),
    val goodPairings: List<String> = emptyList(),
    val avoidAfter: List<String> = emptyList(),
    val overallRating: Float = 0f
)
